/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated/admin/subscribers'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin/admins'
import { Route as AuthenticatedAdminMembersIndexRouteImport } from './routes/_authenticated/admin/members.index'
import { Route as AuthenticatedAdminMembersHashIdRouteImport } from './routes/_authenticated/admin/members.$hashId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMembersIndexRoute =
  AuthenticatedAdminMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMembersHashIdRoute =
  AuthenticatedAdminMembersHashIdRouteImport.update({
    id: '/members/$hashId',
    path: '/members/$hashId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/faq': typeof FaqRoute
  '/get-involved': typeof GetInvolvedRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/members/$hashId': typeof AuthenticatedAdminMembersHashIdRoute
  '/admin/members/': typeof AuthenticatedAdminMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/faq': typeof FaqRoute
  '/get-involved': typeof GetInvolvedRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/members/$hashId': typeof AuthenticatedAdminMembersHashIdRoute
  '/admin/members': typeof AuthenticatedAdminMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/faq': typeof FaqRoute
  '/get-involved': typeof GetInvolvedRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/members/$hashId': typeof AuthenticatedAdminMembersHashIdRoute
  '/_authenticated/admin/members/': typeof AuthenticatedAdminMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/community'
    | '/contact'
    | '/delete-account'
    | '/faq'
    | '/get-involved'
    | '/privacy'
    | '/programs'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/admin/admins'
    | '/admin/messages'
    | '/admin/subscribers'
    | '/admin/'
    | '/admin/members/$hashId'
    | '/admin/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/community'
    | '/contact'
    | '/delete-account'
    | '/faq'
    | '/get-involved'
    | '/privacy'
    | '/programs'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/admins'
    | '/admin/messages'
    | '/admin/subscribers'
    | '/admin'
    | '/admin/members/$hashId'
    | '/admin/members'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/app'
    | '/auth'
    | '/community'
    | '/contact'
    | '/delete-account'
    | '/faq'
    | '/get-involved'
    | '/privacy'
    | '/programs'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/subscribers'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/members/$hashId'
    | '/_authenticated/admin/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  FaqRoute: typeof FaqRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/members/': {
      id: '/_authenticated/admin/members/'
      path: '/members'
      fullPath: '/admin/members/'
      preLoaderRoute: typeof AuthenticatedAdminMembersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/members/$hashId': {
      id: '/_authenticated/admin/members/$hashId'
      path: '/members/$hashId'
      fullPath: '/admin/members/$hashId'
      preLoaderRoute: typeof AuthenticatedAdminMembersHashIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminMembersHashIdRoute: typeof AuthenticatedAdminMembersHashIdRoute
  AuthenticatedAdminMembersIndexRoute: typeof AuthenticatedAdminMembersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminMembersHashIdRoute: AuthenticatedAdminMembersHashIdRoute,
    AuthenticatedAdminMembersIndexRoute: AuthenticatedAdminMembersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  FaqRoute: FaqRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
